pipeline {
    agent any

    stages {
        stage('pre -build') {
            steps {
                sh 'echo Pre-build'
            }
        }

        stage('build') {
            steps {
                sh 'echo Build in progress.'
            }
        }

        stage('Unit tests') {
            steps {
                sh 'echo Running unit tests'
            }
        }

        stage('Regression Tests') {
            steps {
                parallel (
                    chrome: {
                        sh "echo Running in Chrome"
                    },

                    edge: {
                        sh "echo Running in edge"
                    },

                    safari: {
                        sh "echo Running in safari"
                    },

                    firefox: {
                        sh "echo Running in firefox"
                    }
                )
            }
        }

        stage('deploy') {
            steps {
                sh 'echo Deploying build'
            }
        }
        
        stage('Release to prod') {
            steps {
                sh 'echo Releasing to prod'
            }
        }

    }

    post {
        always {
            echo 'Cleanup after everything!'
        }

        success {
            echo "Pipeline succeeded"
        }

        failure {
            echo "Pipeline failed"
        }

    }
}