pipeline {
    agent any

    options{
        retry(3)
    }

    stages {

        stage('deploy') {
            options{
                retry(3)
            }
            
            steps {
                error ("Error")
            }
        }
        
        stage('Release to prod') {
            steps {
                sh 'echo Releasing to prod'
            }
        }

    }
}