pipeline {
    agent any

    environment {
        name = "Ujjwal"
    }
    stages {
        stage("if-else") {
            steps {
                script {
                    if(env.name == "Ujjwal") {
                        echo "I am here"
                    }
                    else {
                        echo "Inside else block"
                    }
                }
            }
        }

        stage("try-catch") {
            steps {
                script {
                    try {
                        error "ERROR!!"
                    }
                    catch(e){
                        echo "Try-catch worked, pipeline should pass"
                    }
                }
            }
        }
    }
}