pipeline {
    agent any

    stages {
        stage('pre-build') {
            stages {
                stage('inner prebuild-1'){
                    steps {
                        sh 'echo Pre-build-inner1'
                    }
                }

                stage('inner prebuild-2'){
                    steps {
                        sh 'echo Pre-build-inner2'
                    }
                }
            }
        }

        stage('build') {
            steps {
                sh 'echo Build in progress.'
            }
        }

        stage('Unit tests') {
            steps {
                sh 'echo Running unit tests'
            }
        }

        stage('Regression Tests') {
            parallel {
                stage("Chrome") {
                    steps {
                        sh "echo Running in Chrome"
                    }
                }

                stage("Edge") {
                    steps {
                        sh "echo Running in edge"
                    }
                }

                stage("Safari") {
                    steps {
                        sh "echo Running in safari"
                    }
                }

                stage("FireFox") {
                    steps {
                        sh "echo Running in firefox"
                    }
                }
                
            }
        }

        stage('deploy') {
            steps {
                sh 'echo Deploying build'
            }
        }
        
        stage('Release to prod') {
            steps {
                sh 'echo Releasing to prod'
            }
        }

    }

    post {
        always {
            echo 'Cleanup after everything!'
        }

        success {
            echo "Pipeline succeeded"
        }

        failure {
            echo "Pipeline failed"
        }

    }
}